[workspace]

resolver = "2"

members = ["crates/*"]

[workspace.dependencies]
ir_aquila = "0.0.2"
reqwest = "0.12.9"
serde = { version = "1.0.216", features = ["derive"] }
snafu = "0.8.5"
tokio = { version = "1.42.0", features = ["rt-multi-thread", "rt", "macros"] }
tracing = "0.1.41"

