[package]
name = "app"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
# Mainly for supporting `egui::containers::Modal`
eframe = { git = "https://github.com/emilk/egui", branch = "master" }
tokio.workspace = true
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
tracing.workspace = true

common = { path = "../common" }