[package]
name = "app"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
eframe = "0.29.1"
egui_extras = "0.29.1"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
tokio = { version = "1.42.0", features = ["rt-multi-thread", "rt", "macros"] }
tracing.workspace = true

common = { path = "../common" }